name: caixafacil
descri0ption: Caixa Fácil PDV

version: 1.0.9+9

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  awesome_dialog: ^3.2.0
  backdrop: ^0.9.1
  bottom_navy_bar: ^6.0.0
  bottomreveal: ^2.0.0
#  catcher_2: ^1.0.7
  cupertino_icons: ^1.0.6
  cpf_cnpj_validator: ^2.0.0
  crypto:  ^3.0.3
  csv: ^5.1.1
  custom_radio_grouped_button: ^2.2.1
  desktop_window: ^0.4.0
  drift: ^2.14.1
  email_validator: ^2.1.17
  encrypt: ^5.0.3
  extended_masked_text: ^2.3.1
  file_picker: ^6.1.1
  flutter_barcode_scanner: ^2.0.0
  flutter_bootstrap: ^2.0.0
  flutter_dotenv: ^5.1.0
  flutter_html: ^3.0.0-beta.1
  flutter_spinbox: ^0.13.1
  #flutter_masked_text: any
  #flutter_sparkline: any
  font_awesome_flutter: ^10.6.0
#  html: ^0.15.4
  image_picker: ^1.0.7
  ini: ^2.1.0
  intl: ^0.18.1
  http: ^1.1.2
  path: ^1.8.3
  path_provider: ^2.1.2
  platform_device_id: ^1.0.1
  printing: ^5.11.1
  provider: ^6.1.1
  sentry_flutter: ^7.14.0
  share_plus: ^7.2.1
  sparkline: ^1.0.0
  sqlite3_flutter_libs: ^0.5.18
  url_launcher: ^6.2.3
  xml: ^6.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#dependency_overrides:
#  catcher_2:
#    git:
#      url: https://github.com/ThexXTURBOXx/catcher.git

dev_dependencies:
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  flutter_launcher_icons: 0.13.1
  flutter_lints: ^3.0.1
  msix: ^3.16.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/text/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/launcher_icon.png'

msix_config:
  display_name: T2Ti Pegasus PDV
  publisher_display_name: T2Ti.COM
  identity_name: T2Ti.COM.T2TiPegasusPDV
  msix_version: 1.0.10.0
  publisher: CN=0A6E4754-6ACC-44ED-81F6-94B57BF2E8BC
  logo_path: C:\T2Ti ERP\ERP 3.0 Programas e Fontes\Flutter\pegasus_pdv\assets\images\logo_pegasus_pdv.png
  capabilities: internetClient,systemManagement,pointOfService,bluetooth
  store: true
